rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.1

notifications:
  email:
    - robert.e.hallgren@hp.com
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2.1"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.3"
    - PUPPET_GEM_VERSION="~> 4.3.2"

matrix:
  exclude:
    - rvm: 2.2.1
      env: PUPPET_GEM_VERSION=3.2.1
    - rvm: 2.2.1
      env: PUPPET_GEM_VERSION=3.3.0
    - rvm: 2.2.1
      env: PUPPET_GEM_VERSION=3.4.3

