---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3" STRICT_VARIABLES="no" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES="no"

sudo: false

script: 'bundle exec metadata-json-lint metadata.json && bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3.4.0" STRICT_VARIABLES="no"
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="no"
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="no"
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="no"
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES="no"
    - rvm: 2.2.0
      env: PUPPET_GEM_VERSION="~> 3" STRICT_VARIABLES="no" FUTURE_PARSER="yes"

notifications:
  email: false
